### ISSUE TITLE
iPad issue 

### ISSUE THREAD

**Issue by sallyahmed** [gelemias/RDGliderViewController-Swift#2]
i make bottom top view 

 self.bottomToTopGlideVC = RDGliderViewController.init(parent: self,
                                                              WithContent:widgetModule,
                                                              AndType: .RDScrollViewOrientationBottomToTop,
                                                              WithOffsets: [1, 0.1])

and not appear in iPad with length 170

**Comment by gelemias** [comment]
@sallyahmed are you changing the _widgetModule_ frame?
here is the initialisation for your user case.

![bottomtotop170](https://cloud.githubusercontent.com/assets/15629719/26045314/e52d4fdc-3949-11e7-88f9-1e5936b4f34f.gif)

Is this the behaviour you were expecting?

**Comment by gelemias** [comment]
I will close this issue since seems to have been resolved.
